openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /account/company/:
    post:
      operationId: account_company_create
      tags:
      - account
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
  /account/login/:
    post:
      operationId: account_login_create
      tags:
      - account
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeLogin'
          description: ''
  /account/profile/:
    get:
      operationId: account_profile_retrieve
      tags:
      - account
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeProfile'
          description: ''
  /account/register/:
    post:
      operationId: account_register_create
      tags:
      - account
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeRegistration'
          description: ''
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /device/:
    get:
      operationId: device_retrieve
      tags:
      - device
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
          description: ''
    post:
      operationId: device_create
      tags:
      - device
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /device/{id}/:
    get:
      operationId: device_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - device
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: device_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - device
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: device_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - device
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /device/checkout/:
    get:
      operationId: device_checkout_retrieve
      tags:
      - device
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Checkout'
          description: ''
    post:
      operationId: device_checkout_create
      tags:
      - device
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /device/checkout/{id}/:
    get:
      operationId: device_checkout_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - device
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Checkout'
          description: ''
  /device/checkout/return/{id}/:
    post:
      operationId: device_checkout_return_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - device
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnDevice'
          description: ''
components:
  schemas:
    Checkout:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        checked_out_at:
          type: string
          format: date-time
          readOnly: true
        checked_in_at:
          type: string
          format: date-time
          nullable: true
        condition_on_checkout:
          type: string
        condition_on_return:
          type: string
        device:
          type: integer
        employee:
          type: integer
      required:
      - checked_out_at
      - device
      - employee
      - id
    Company:
      type: object
      properties:
        company_name:
          type: string
          maxLength: 255
        employee:
          allOf:
          - $ref: '#/components/schemas/EmployeeRegistration'
          writeOnly: true
      required:
      - company_name
      - employee
    CompanyDetail:
      type: object
      properties:
        company_name:
          type: string
      required:
      - company_name
    Device:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        device_type:
          type: string
          maxLength: 255
        serial_number:
          type: string
          maxLength: 255
        checked_out:
          type: boolean
        company:
          type: integer
      required:
      - company
      - device_type
      - id
      - serial_number
    EmployeeLogin:
      type: object
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        password:
          type: string
          maxLength: 128
      required:
      - email
      - password
    EmployeeProfile:
      type: object
      properties:
        company:
          $ref: '#/components/schemas/CompanyDetail'
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 255
        name:
          type: string
          maxLength: 200
      required:
      - company
      - email
      - id
      - name
    EmployeeRegistration:
      type: object
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        name:
          type: string
          maxLength: 200
        password:
          type: string
          writeOnly: true
          maxLength: 128
        password2:
          type: string
          writeOnly: true
      required:
      - email
      - name
      - password
      - password2
    ReturnDevice:
      type: object
      properties:
        checked_in_at:
          type: string
          format: date-time
          nullable: true
        condition_on_return:
          type: string
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
